---
ansible_connection: local
openshift_cluster_content:
- object: ruby-components
  content:
  - name: ruby-ex
    template: "{{ playbook_dir }}/templates/app/ruby.yml"
    params: "{{ playbook_dir }}/params/app/ruby"
    namespace: "{{ dev.namespace }}"
    tags:
    - app
